"""添加用户实名认证字段

Revision ID: 9394060fb488
Revises: 
Create Date: 2026-02-10 01:31:46.172837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9394060fb488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('id_card', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('phone')
        batch_op.drop_column('id_card')
        batch_op.drop_column('real_name')

    # ### end Alembic commands ###
